### ISSUE TITLE
serviceaccount impersonation fails

### ISSUE THREAD

**Issue by adabuleanu** [projectcapsule/capsule-proxy#388]
# Bug description

While working with flux and the multitenancy setup, flux is not able to impersonate the service account which is tenant owner. This happened after upgrade from capsule-proxy `v0.4.5` to `v0.5.0`. 

# How to reproduce

1. Install capsule and capsule proxy `v0.5.0`.
2. [Install flux](https://fluxcd.io/flux/installation/).
3. Create a tenant with the owner the sa `gitops-reconciler` and a tenant namespace
More details on https://github.com/maxgio92/capsule-gitops-testing/

# Expected behavior

Service account should be impersonated and flux reconciliation should not fail.

# Logs
Flux reconciliation logs:
```
my-kustomization       my-namespace                            XXXXXX        False           False   timeout waiting for: [Namespace/my-namespace: 'Unknown': namespaces is forbidden: User "system:serviceaccount:my-namespace:gitops-reconciler" cannot list resource "namespaces" in API group "" at the cluster scope]      
```

Capsule-proxy error:
```
{"level":"error","ts":"2024-02-09T14:01:48.606Z","msg":"Reconciliation failed after 30.767523613s, next try in 1m0s","controller":"kustomization","controllerGroup":"kustomize.toolkit.fluxcd.io","controllerKind":"Kustomization","Kustomization":{"name":"my-kustomization","namespace":"my-namespace"},"namespace":"my-namespace","name":""my-kustomization","reconcileID":"XXXXXX","revision":"XXXXXXX","error":"timeout waiting for: [Namespace/my-tenant-namespace status: 'Unknown': namespaces is forbidden: User \"system:serviceaccount:my-namespace:gitops-reconciler\" cannot list resource \"namespaces\" in API group \"\" at the cluster scope]"}
```

# Additional context

This was initially posted in https://github.com/projectcapsule/capsule-proxy/issues/349 and the fix was proposed for `v0.4.7` release, but unfortunately I still get the issue in the latest `v0.5.0` release. The only workaround is to downgrade to `v0.4.5`. More details can be found in  https://github.com/projectcapsule/capsule-proxy/issues/349 as the issue is identical.

**Comment by oliverbaehler** [comment]
Could you share your capsuleConfiguration?

**Comment by mtheeren-asml** [comment]
Hi Oliver, me and Adrian are working on the same project. The configuration is:
```
apiVersion: capsule.clastix.io/v1beta2
kind: CapsuleConfiguration
metadata:
  labels:
    app.kubernetes.io/instance: capsule
    app.kubernetes.io/name: capsule
    app.kubernetes.io/version: 0.3.2
  name: default
spec:
  enableTLSReconciler: false
  forceTenantPrefix: true
  overrides:
    TLSSecretName: capsule-tls
    mutatingWebhookConfigurationName: capsule-mutating-webhook-configuration
    validatingWebhookConfigurationName: capsule-validating-webhook-configuration
  protectedNamespaceRegex: ""
  userGroups:
  - system:authenticated
```
