### ISSUE TITLE
malformed HTTP Response

### ISSUE THREAD

**Issue by naivary** [projectcapsule/capsule-proxy#589]
# Bug description

When I'm using the following command:

```bash
kubectl get ns --kubeconfig=alice-oil-oil.kubeconfig --insecure-skip-tls-verify
```
I get the following error message: Unable to connect to the server: malformed HTTP response "\x00\x00\x12\x04\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x80\x00\x04\x00\x01\x00\x00\x00\x05\x00\xff\xff\xff\x00\x00\x04\b\x00\x00\x00\x00\x00\x7f\xff\x00\x00\x00\x00\b\a\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01"

# How to reproduce

Run the [create-user.sh](https://github.com/projectcapsule/capsule/blob/main/hack/create-user.sh) script using `alice-oil` as the first and `oil` as the second parameter.

Create a `tenant` which is owned by the user `alice-oil`.

Install capsule-proxy with the following `helm` command:

```bash
helm upgrade --install capsule-proxy projectcapsule/capsule-proxy \
   --namespace capsule-system \
   --set crds.install=true \
   --set ingress.enabled=true \
   --set ingress.className="nginx" \
   --set ingress.hosts[0].host="capsule.mh.com" \
   --set ingress.hosts[0].paths[0]="/" \
   --set ingress.tls[0].secretName="capsule-proxy-tls" \
   --set ingress.tls[0].hosts[0]="capsule.mh.com" \
   --set certManager.issuer.name="self-signed" \
   --set certManager.issuer.kind="ClusterIssuer" \
   --set certManager.generateCertificates=true \
   --set ingress.annotations."nginx\.ingress\.kubernetes\.io/backend-protocol"="HTTPS" \
   --set ingress.annotations."nginx\.ingress\.kubernetes\.io/force-ssl-redirect"='"true"' \
```

Set `https://capsule.mh.com` as the `proxy-url` in the `alice-oil-oil.kubeconfig`.

NOTE: Make sure to use a host which can be resolved by your system e.g. `capsule.mh.com` is probably not resolving on your system.

# Expected behavior

I expected to be able to create the namespace like in the usual manner.

# Logs

If applicable, please provide logs of `capsule`.

In a standard stand-alone installation of Capsule,
you'd get this by running `kubectl -n capsule-system logs deploy/capsule-proxy`.

# Additional context

```yaml
# capsule-proxy ingress rule

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    meta.helm.sh/release-name: capsule-proxy
    meta.helm.sh/release-namespace: capsule-system
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
  creationTimestamp: "2024-12-05T11:12:14Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: capsule-proxy
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: capsule-proxy
    app.kubernetes.io/version: 0.8.0
    helm.sh/chart: capsule-proxy-0.8.0
  name: capsule-proxy
  namespace: capsule-system
  resourceVersion: "352513"
  uid: ba2d2be4-f706-4802-9d0d-ff2455dd6a99
spec:
  ingressClassName: nginx
  rules:
  - host: capsule.mh.com
    http:
      paths:
      - backend:
          service:
            name: capsule-proxy
            port:
              number: 9001
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - capsule.mh.com
    secretName: capsule-proxy-tls
status:
  loadBalancer:
    ingress:
    - ip: 192.168.56.100
```

- Capsule-Proxy version: latest
- Helm Chart version: capsule-proxy-0.8.0     app-version: 0.8.0
- Kubernetes version: 
  Client Version: v1.31.1
  Kustomize Version: v5.4.2
  Server Version: v1.31.1

**Comment by prometherion** [comment]
Thanks for the report, @naivary.

May I ask you if you're using a token-based authentication, or relying on the client-certificate one?

Furthermore, how do you ensure NGINX uses the right certificate for the TLS connection to the upstream servers? AFAIK, you should specify one.

**Comment by naivary** [comment]
I'm using a client-certificate one e.g. X.509 certificate via the script. How should I specify the correct certificate?

**Comment by prometherion** [comment]
Unfortunately, it wouldn't work: you're performing a TLS termination at the Ingress Controller, and the client certificates are not proxy-passed to the upstream servers.

You have multiple options here:
1. TLS/SSL passthrough to Capsule Proxy (and client certificate auth will work)
2. TLS/SSL termination at the Ingress Controller, and proxy pass to plain HTTP with Bearer Token
3. TLS/SSL termination at the Ingress Controller, and upstream to Capsule Proxy in HTTPS (this is the most challenging, and however, you'll lose client-certificate authentication)

**Comment by naivary** [comment]
I will try it! Thank you. You got any sources for the first option? I'm using a nginx ingress controller

**Comment by naivary** [comment]
I configured my nginx ingress controller to allow SSL Passthrough and used int for the ingress rule too but still get the same error.

Using the following kubeconfig:

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJWmNaaW1JQ0Q5VDB3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRFeE1USXhNekkyTURGYUZ3MHpOREV4TVRBeE16TXhNREZhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURMUXI1ZkpWREhDOE9nY0lyYzlWUzlkT0ZxdDVzSjI5NGhsdis2ajhKV0tMaTU0T3J2K3gvSUp6ejgKanQ2WmNMOERoaGtlMkdFQnE5SVV6dHAxNlhiSjZQb3FidTdmSUlSSm1iY1pldWJ5MHo4eTJTNFZ6RzFVdWQrWQpESytyOU1GNEJITUozUjdOOHh1QmtoWDdFa0tZd0p0dnlHSUFROGdveVV2Q1lQN3hFSUp0ZTE5S3F0K1l4Wm1yClFET0lyaWJTNXVNRzFpYXZhZ0V3V2JSNkE1QUkvVVgrNzBaTmVQdlJHT2JOQXZQUFBxZE1pakxoUlJNYTg4OUQKZ1duY2hBcU42czBuc1RjRWdnMVIrOCtvOWRYL00rY3ZtQmEwbk82U3hwb2E1OUFxeTlyNXkzU1o3RDc3MVJPTApSYmhRSlZBUGdvL25CQ0I0b3J3UzRTWlM0dk85QWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRR3hCTEVESkpSTjNCeU53Vnh3VEhuaFAwdkRqQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQzVoZURWdzc5VgptYmMxeG1KZVJrdkVIUnpLbDU0YW5ObjBDZ3ZLQ2tJVWxibWgyZE9JbVUza3M4RU83VEFBcTlDUDZvckdvS0VZCnJFTU9VUGRmRUdNOTVMeXpxanlPWUFaejYzZHdBZGJNb01NRkJRZ2FXZzZUeE41enBkRnRldGFEMlhEWXlPK0IKYXZZcEc4WStRYzVvbHZqQU84OW05RFV5UGM1MEtpNnh5TlBlOFA5Wldnb3NWUkFxdzdRb3p4ZHNFOTMzVkxJegpWVk1pT25nOExJQ3hNc0oyeVdrSEpTRkxLdmpvdkprTnA3Ym1heFlrNVFCSGQ0WHR3Tk1GeExNSHdyMFcyNGhQCi9rM1RYUE13RGxoZThNQ052WDFiTVA0NmxEYkZCc2cwLzQ0NGlhbXNncG1CMVN3OFhleEc3YytlNThRc3J1alEKOVhiaWpudTlLYXAwCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    proxy-url: https://capsule.mh.com
    server: https://192.168.56.61:6443
  name: cluster.local
contexts:
- context:
    cluster: cluster.local
    user: alice-oil
  name: alice-oil-oil
current-context: alice-oil-oil
kind: Config
preferences: {}
users:
- name: alice-oil
  user:
    client-certificate: alice-oil-oil.crt
    client-key: alice-oil-oil.key

```
