### ISSUE TITLE
Conditional flag prevents capsule-proxy-certgen Job creation and fails upgrade

### ISSUE THREAD

**Issue by heytrav** [projectcapsule/capsule-proxy#643]
# Bug description

The conditional [around creating the _proxy certgen job_](https://github.com/projectcapsule/capsule-proxy/blob/bdbf35bc86e75e125e8f13c5702e0f9433ac36f5/charts/capsule-proxy/templates/certgen-job.yaml#L4) prevents the Job from being created and causes Capsule upgrade to fail.

# How to reproduce

I'm using FluxCD and currently have the following in my values
```
  values:
    serviceMonitor:
      enabled: true
    proxy:
      enabled: true
    certManager:
      generateCertificates: true
    # tls:
    #   enableController: false
    fullnameOverride: capsule-capsule

```
I believe the conditional mentioned above is preventing the Job from being created. This is probably fine, however the missing Job is causing FluxCD to fail upgrading capsule https://github.com/projectcapsule/capsule/issues/1360.

I'm not sure if this is a bug with this repo or with capsule (or FluxCD).

# Expected behavior

# Logs

If applicable, please provide logs of `capsule`.

In a standard stand-alone installation of Capsule,
you'd get this by running `kubectl -n capsule-system logs deploy/capsule-proxy`.

# Additional context

- Capsule-Proxy version: (`capsule-proxy --version`)
- Helm Chart version: (`helm list -n capsule-system`)
- Kubernetes version: (`kubectl version`)
