### ISSUE TITLE
Listing PersistentVolumes isn't possible with ProxySetting

### ISSUE THREAD

**Issue by sandert-k8s** [projectcapsule/capsule-proxy#668]
# Bug description
First of all, thanks for the great addition of adding the ProxySetting. We really like the implementation of it! We have made some good progress with getting Velero to work as a tenant owner. When done, we'll share it and edit the current velero doc on the capsule website :) 

Bug: 
Listing PersistentVolumes isn't possible. We keep getting: 

```
Error from server (BadRequest): Unable to list "/v1, Resource=persistentvolumes": not allowed
```
ProxySetting:
```
---
apiVersion: capsule.clastix.io/v1beta1
kind: ProxySetting
metadata:
  name: test
  namespace: oil-tests-velero-customer1
spec:
  subjects:
  - kind: ServiceAccount
    name: velero-server
    clusterResources:
    - apiGroups:
      - ""
      resources:
      - persistentvolumes
      operations:
      - List
      selector:
        matchLabels:
          capsule.clastix.io/tenant: oil-tests
```

# How to reproduce

Create a pvc as tenant owner, a pv is created: 
```
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pvc-uid
  labels:
    capsule.clastix.io/tenant: oil-tests
```
Apply the ProxySetting as above, and try getting the persistent volume as the specified subject (in this case Service account velero-server): 
```
Error from server (BadRequest): Unable to list "/v1, Resource=persistentvolumes": not allowed
```

Other resources do work we specify in the ProxySetting.

# Expected behavior

Something like:
```
@Mac velero % k get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                       STORAGECLASS                  VOLUMEATTRIBUTESCLASS   REASON   AGE
pvc-uid   200Mi      RWO            Delete           Bound    oil-tests-db/test-db-correct-multi-2   ocs-storagecluster-ceph-rbd   <unset>                          
```

# Additional context

- Capsule-Proxy version: 0.9.1
- Helm Chart version: 0.9.1
enabled feature gates:
```
        - '--feature-gates=ProxyAllNamespaced=true'
        - '--feature-gates=ProxyClusterScoped=true'
```

**Comment by sandert-k8s** [comment]
Ah, it does work if we put it in the tenantSpec, so my issue is resolved. 

But, putting it in the ProxySetting like the [docs](https://capsule.clastix.io/docs/general/proxy/#cluster-scoped-resources-selection-strategy-precedence) said doesnt work:
```
    proxySettings:
    - kind: PersistentVolumes
      operations:
      - List
 ```
What is also kinda interesting is the apispec in the [docs](https://capsule.clastix.io/docs/general/proxy/#cluster-scoped-resources-selection-strategy-precedence), it says `v1beta2`, but as far as I see, there is only `v1beta1` for the ProxySetting.

**Comment by oliverbaehler** [comment]
Regarding the permissions, that's correct. Currently i have it implemented, that only clusterResources are added, which we did not already support. But i am happy to change that.

Can you try with 

```yaml
    - kind: ServiceAccount
      name: system:serviceaccount:oil-tests-velero-customer1:velero-server
      proxySettings:
        - kind: PersistentVolumes
          operations:
            - List
        - kind: StorageClasses
          operations:
            - List   
  storageClasses:
    matchExpressions:
    - { key: name, operator: In, values: [ceph, other] }
```

Otherwise i will need some logs
