### ISSUE TITLE
ProxyAllNamespaced doesn't work for additionalRoleBindings

### ISSUE THREAD

**Issue by sandert-k8s** [projectcapsule/capsule-proxy#736]
# Bug description

When I add some `AdditionalRoleBindings` in the tenant spec for a certain user (which isn't part of the owner group), the `--all-namespaces` flag returns that there are zero resources. When this user with the exact same rolebinding is added as owner instead of additonalRoleBinding, it immidiately works.
`--feature-gates=ProxyAllNamespaced=true` is set to enable the ProxyAllNamespaced feature.

# How to reproduce

```
spec:
  additionalRoleBindings:
    - clusterRoleName: external-secrets-controller
      subjects:
        - kind: ServiceAccount
          name: external-secrets
          namespace: external-secrets-namespace

```
Results in: 
```
k get secretstore -A                            
No resources found
```

But this user does have permissions to that resource, because if i check it with the namespace, it does appear:
```
kubectl get secretstore -n secret-store-test
NAME                  AGE     STATUS   CAPABILITIES   READY 
secret-store   7m22s   
```

When I add this serviceAccount as owner instead via the additionalRoleBindings, it does work:
```
spec:
  owners:
    - clusterRoles:
        - external-secrets-controller
      kind: ServiceAccount
      name: 'system:serviceaccount:external-secrets-namespace:external-secrets'
```
Results in:
```
k get secretstore -A
NAMESPACE               NAME                  AGE   STATUS   CAPABILITIES   READY
secret-store-test  secret-store   10m   Valid    ReadOnly       True
```

# Expected behavior

I expected that I would also get the resources with the `--all-namespaces` flag when a users is only granted access rights that were set with additionalRoleBindings.

- Capsule-Proxy version: 0.9.5
